// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/task.proto

package task

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Task service

func NewTaskEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Task service

type TaskService interface {
	RecordTask(ctx context.Context, in *RecordRequst, opts ...client.CallOption) (*RecordResponse, error)
}

type taskService struct {
	c    client.Client
	name string
}

func NewTaskService(name string, c client.Client) TaskService {
	return &taskService{
		c:    c,
		name: name,
	}
}

func (c *taskService) RecordTask(ctx context.Context, in *RecordRequst, opts ...client.CallOption) (*RecordResponse, error) {
	req := c.c.NewRequest(c.name, "Task.RecordTask", in)
	out := new(RecordResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Task service

type TaskHandler interface {
	RecordTask(context.Context, *RecordRequst, *RecordResponse) error
}

func RegisterTaskHandler(s server.Server, hdlr TaskHandler, opts ...server.HandlerOption) error {
	type task interface {
		RecordTask(ctx context.Context, in *RecordRequst, out *RecordResponse) error
	}
	type Task struct {
		task
	}
	h := &taskHandler{hdlr}
	return s.Handle(s.NewHandler(&Task{h}, opts...))
}

type taskHandler struct {
	TaskHandler
}

func (h *taskHandler) RecordTask(ctx context.Context, in *RecordRequst, out *RecordResponse) error {
	return h.TaskHandler.RecordTask(ctx, in, out)
}
